### ISSUE TITLE
Adding an update log.

### ISSUE THREAD

**Issue by ZombieStriker** [ArsenArsen/Updater#1]
Every time a plugin updates, the name of the plugin and the time should be logged in a text file somewhere (E.g. Updater/logs.txt). This will allow the server host to see if a plugin is updating too frequently and, in the case of potentially malicious code being updated, allow server owners to see which plugins may have done it.

**Comment by ArsenArsen** [comment]
Good idea! I will do this tonight. Thanks for suggesting! Would go well with the fact that I make backups.

**Comment by ArsenArsen** [comment]
Done!

Thanks for suggesting it, very good idea!
