### ISSUE TITLE
File names cannot have spaces bug.

### ISSUE THREAD

**Issue by ZombieStriker** [ArsenArsen/Updater#3]
I have just updated some of my plugins to use this updater, and I ran into a bug. If the plugin has a space in it's name when your updater tries to get the file's location, it will replace the space with "%20". Because of this, names of the files of plugins should have an underscore ("_") instead of a space.
The thing is, when I upload the version to bukkit-dev, the name has to have a space in it in order for you updater to parse the version.

You can either make it so the auto updater parses both "[Space]v" and "_v" for BukkitDev, or create a 'hack' to turn all %20 in the file's pathname to spaces (which I would recommend).

**Comment by ArsenArsen** [comment]
Interesting.. I'll do a Html decode on the string. Can I have a link to the plugin please? 

Also Ill have to do this tommorow, no time right now. 

Thanks for reporting

**Comment by ZombieStriker** [comment]
https://dev.bukkit.org/bukkit-plugins/lobbyapi/
https://dev.bukkit.org/bukkit-plugins/music/

These two plugins have this issue. If you edit the plugin.yml to have a lower version number, it will attempt to copy the "backup" file and print out an error.

**Comment by ArsenArsen** [comment]
Can you try again with 1.1.5-R0.1-SNAPSHOT and https://repo.arsenarsen.com/content/repositories/snapshots/ as the new repository. For some reason, even if it does pass my unit tests, I cannot test it. 

Thanks.

**Comment by ZombieStriker** [comment]
The new snhapshot fixed this issue.

**Comment by ArsenArsen** [comment]
Great. Thanks again, have a good day.
